# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GanClientTester' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

   pod 'RxSwift',    '~> 5'
   pod 'RxCocoa',    '~> 5'

end


# fixed compile warning:
# The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings.delete ‘IPHONEOS_DEPLOYMENT_TARGET’
	end
    end
end
